version: '3'

services:
  chromadb:
    image: chromadb/chroma
    container_name: chroma
    networks:
      - vector_stores
    ports:
      - "8000:8000"  # Adjust the port as needed

networks:
  vector_stores:
    external: True
    
