version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: talkaroo_user_interface
    environment:
      - AUTH0_SECRET=${AUTH0_SECRET}
      - AUTH0_BASE_URL=${AUTH0_BASE_URL}
      - AUTH0_ISSUER_BASE_URL=${AUTH0_ISSUER_BASE_URL}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
    ports:
      - 3000:3000
    networks:
      - talkaroo
    env_file:
      - .env

  response_creation_aggregation:
    build: 
      context: ./response_creation_aggregation
      dockerfile: Dockerfile
    container_name: response_creation_aggregation
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "30500:5000"
    restart: always
    volumes:
      - "./response_creation_aggregation:/project"
    networks: 
      - talkaroo
    env_file:
      - .env


  chromadb:
    image: chromadb/chroma
    container_name: chroma
    ports:
      - "8000:8000"  # Adjust the port as needed
    env_file:
      - .env

networks:
  talkaroo:
    driver: bridge